import unicodedata

def normalize(s):
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return s.lower().strip()

db_names_raw = [
    "Abarca Mamani Ismael Maurice","Abello Navarro Cristian Eduardo","Aguilar Damacase Jesus Enrique",
    "Alanis Pozo Maria Jose Del Pilar","Alarcon Mino Sofia Esperanza","Alcayaga Chellew Alan Christian",
    "Alfaro Miranda Cristian Antonio","Alfaro Zapata Alejandra Salome","Alvarez Pardo Bastian Maximiliano",
    "Alvarez Trittini Valentina Paz","Alvina Mondaca Patricio Fernando","Andronico Cangana Javier Enrique",
    "Andueza Rodriguez Maria Ignacia","Aramayo Fritis Victor Marcos","Aravena Arriagada Camilo Ernesto",
    "Araya Chanqueo Ignacio Isaac","Araya Retamales Sebastian Josue","Arce Rojas Camilo Alfonso",
    "Arredondo Andrade Felipe","Artiles Zerpa Alejandro","Barraza Lamas Pia Noelia",
    "Barreda Torres Felix Wilson","Bernales Magnere Tomas Augusto","Beroiza Rodriguez Daniela Andrea",
    "Bracamonte Aballai Carlos Pascual","Buch Guzman Oscar Eduardo","Bueno Figueroa Ivan Hugo",
    "Bugueno Solar Sergio Alberto","Bustamante Rojas Rodrigo Andres","Cabrera Almuna Felipe Esteban",
    "Campos Llanca Luis Humberto","Cancino Toloza Daniel Andres","Carmona Castro Alvaro Rodrigo",
    "Carrasco Rojas Erick Fernando","Carreno Madrid Milko Giovanni","Cartagena Aravena Gloria Stephanie",
    "Cartagena Perez Daniela Andrea","Carvallo Saez Micchelle Yamil","Castillo Mendez Diego Antonio",
    "Castillo Valderrama Carlos Sebastian","Castro Rojas Katherina Fernanda","Cataldo Leiva Paola Andrea",
    "Caucoto Meneses Carolina Angelica","Cepeda Vivanco Pilar Victoria","Chimaja Olguin Manuel Andres",
    "Cid Sandoval Nicolas Andre","Contador Cortes Julian","Cortes Salazar Jaime Saul",
    "Cruz Mora Mariela Concepcion","Cuevas Cortes Fernanda Javiera","Delgado Galleguillos Dario Andres",
    "Delgado Inostroza Paulina Alejandra","Delgado Rojo Rodrigo Alfredo","Diaz Correa Belfor Salvador Abel",
    "Diaz Aguilar Gabriela Alexandra","Diaz Herrera Nicolas Felipe","Diaz Lara Camila",
    "Echeverria Noton Loreto Cecilia","Escoda Valenzuela Josefa Constanza","Fernandez Ortiz Hernan Felipe",
    "Fernandez Rincon Johana Idaly","Flores Alquinta Pablo Alejandro","Freire Meza Graciela Constanza",
    "Fuentes Rubio Lenka Camila","Fuenzalida Maureira Oscar Patricio","Garin Madariaga Guillermo Alberto",
    "Garrido Yanez Hector Manuel","Garro Castano Valentina","Gomez Leiva Maria Jose",
    "Gomez Moyano Camila Javiera","Gonzalez Zavala Pablo Andres","Gonzalez Gamboa Iris Lorena",
    "Guzman Cortes Abdiel Alexis","Gomez Crawford Isidora Paz","Gomez Fierro Felipe Urbano",
    "Gomez Sanchez Fernanda Javiera","Harrison Necochea Benjamin","Harrison Necochea Victor Andres",
    "Heredia Duran Viviana Elizabeth","Hernandez Suarez Valentina Paz","Herrera Mauad Roberto Antonio",
    "Huidobro Maturana Fabiani Alejandro","Illanes Caba Deborah Nicole","Iriarte Magadan Paula Amaya",
    "Iriarte Martinez Ana Belen","Jara Ulloa Rocio Belen","Julia Perez Carolina Francesca",
    "Jullian Roig Juan Francisco","Kampf Roa Max Andreas","Kaufman Soza Daniel",
    "Kovacic Madariaga Tonkiza Dayann","Lanoy Molina Maglenis Carolina","Lara Oviedo Luis Alexis",
    "Ledezma Hidalgo Alejandro Esteban","Leiva Varela Alejandro Antonio","Lillo Lichsinger Macarena Andrea",
    "Lingua Moreno Aldo Javier","Lopez Condori Daniela Esperanza","Lopez Matamala Marcelo Andres",
    "Lopez Torres Pia Francisca","Lopez Vega Rosalia Libertad","Maluenda Acevedo Camila Alejandra",
    "Mancilla Ordenes Oscar Alonso","Martinez Lazcano Adrian Antonio","Martinez Amenabar Eustaquio",
    "Martinez Perez Yaredla Catalina","Maya Gonzalez Javiera Nicole","Melendez Ruiz Soledad Paola",
    "Mella Cadiz Cristopher Andres","Mellado Salazar Luis","Merino Cereijo Alejandro Francisco",
    "Meza Iriarte Edmundo Esteban Jesus","Middleton Bezanilla Javier Fernando","Miranda Humeres Patricio Javier",
    "Minano Ubeda Blanca Margarita","Molina Tapia Alexis Rodrigo","Montecino Lemus Jose Francisco",
    "Montoya Lopez Diego Ignacio","Moore Rivas Andres Claudio","Moraga Morey Maria Jose",
    "Morales Cuello Cristian Marcelo","Morales France Mauricio Javier","Morales Leiva David Eduardo",
    "Moreno Saavedra Juan Patricio","Mura Gonzalez Minelly Dannay","Munoz Baratta Maria Alejandra",
    "Munoz Camilo Ricardo Ignacio","Munoz Espinoza Ricardo Hernan","Munoz Torres Veronica Viviana",
    "Munoz Vera Manuel Jesus","Navarro Lopez Javier Andres","Neder Acosta Ulises Patricio",
    "Nieto Carcamo Jean Carlos","Norambuena Fuentes Jeannette Lorena","Olivares Vega Alejandra Hortensia",
    "Olmos Riveros Camila Loretto","Orellana Riquelme Felipe Andres","Ortiz Aguilera Sebastian Ignacio",
    "Ovando Vergara Macarena Francisca","Palacios Gomez Ivan Andres","Palma Martinez Delia Geraldina",
    "Palma Zepeda Nancy Anarella","Parra Espinosa Karen Andrea","Pereira Molina Lorena Antonieta",
    "Pincheira Pavez Francisco Emir","Pizarro Bravo Monica Isabel","Pollmann Fleming Sibila Joaquina",
    "Ponce Vidal Claudia Ayleen","Pradenas Meneses Javiera Andrea","Prado Garcia-Huidobro Maria Ignacia",
    "Prieto Zanartu Pablo Alejandro","Perez Arrano Camila Ignacia","Perez Caro Gabriela Ximena",
    "Quintanilla Dominguez Sebastian Ignacio","Ramos Galleguillos Javier Ignacio","Ramos Valenzuela Felipe Antonio",
    "Ramirez Gonzalez Carolina","Ramirez Vega Jasmin Betsabe","Reyes Guzman Mitzi Andrea",
    "Rivera Cerda Hernando Sebastian","Rivera Zarricueta Constanza Nicole","Roa Abayay Marta Soledad",
    "Rodas Araya Carlos Alejandro","Rodriguez Correa Daniela","Rodriguez Gonzalez Alberto Antonio",
    "Rodriguez Varela Maria Paz","Rojas Aubrio Juan Marco","Romero Moraga Fernanda Maria",
    "Ronda Ortiz Antonia Ester","Rozas Toloza Natalia Catalina","Ruiz Ruiz Elizabeth Lissette",
    "Saavedra Lopez Bryan David","Salazar Guerrero Tamara Jose","Salazar Pinto Ana Maria Veronica",
    "Salinas Lizama Javiera Elisa","Salinas Valdivia Omar Andres","Salles Sapag Maria Bernardita",
    "Sanchez Marin Maria Jose","Santana Alcaino Paulina Fernanda","Saunders Menares Barbara Esclava",
    "Silva Amigo Ignacia Margarita","Silva Gatta Sebastian Andres","Solar De La Maza Sofia Macarena",
    "Solari Diaz Gino Guillermo","Soto Rojo Ricardo Alejandro","Sotomayor Villarroel Mauricio Andres",
    "Sanchez Cortes-Monroy Javiera Pilar","Tapia Ahumada Francisco Javier","Toledo Andrade Carla Andrea",
    "Torres Benapres Cristobal Arturo","Torres Gomez Andres Antonio","Trincado Huanchicay Rocio Abril",
    "Urtubia Avalos Fernanda Macarena","Valdes Tapia Josefa Antonieta","Valenzuela Dellafiori Paula",
    "Valeria Coronado Gonzalo Andres","Vallejos Opazo Matias","Valverde Onate Karla Stefanie",
    "Varas Roco Jonathan Andres","Vargas Garcia Pablo Andres","Vargas Moya Exequiel Ananias",
    "Vega Chelme Claudio Andres","Vega Velozo Valeria Andrea","Vergara Pinnola Vannia Silvana",
    "Vidal Diaz Mauricio Antonio","Viedma Calderon Juan Pablo Abelardo","Viera Gallegos Constanza Belen",
    "Vilches Vergara Andrea Makarena","Villalba Campos Catalina De Los Angeles","Villarroel Perez Carmen Gloria",
    "Vasquez Caro Roberto Javier Ramon","Veliz Saavedra Joao Humberto","Worthington Ramirez Aida Constanza",
    "Zamora Marchant Sebastian","Zazzali Toledo Lorenzo Sebastian","Alvarez Alarcon Felipe Martin",
    "Alvarez Espinoza Manuel Octavio","Alvarez Henriquez Valentina Eneyde","Alvarez Ramirez Fernanda Patricia",
]

db_set = set(normalize(n) for n in db_names_raw)

# Listado del usuario (nombre completo tal como aparece)
user_assignments = [
    ("Abarca Mamani Ismael Maurice", "Comunicaciones", "AMSA (ZALDIVAR)"),
    ("Abello Navarro Cristian Eduardo", "Comunicaciones", "CANDELARIA"),
    ("Aguilar Damacase Jesus Enrique", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Alanis Pozo Maria Jose Del Pilar", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Alarcon Mino Sofia Esperanza", "Comunicaciones", "CODELCO DET, KINROSS COMUNICACIONES"),
    ("Alcayaga Chellew Alan Christian", "Comunicaciones", "AMSA (NCEN)"),
    ("Alcayaga Chellew Alan Christian", "Consultoria", "AMSA (NCEN), PROVEEDORES Y FUTUROS LOCALES BHP, SALAR"),
    ("Alvarez Alarcon Felipe Martin", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Alvarez Espinoza Manuel Octavio", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Alvarez Ramirez Fernanda Patricia", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Andronico Cangana Javier Enrique", "Comunicaciones", "GLENCORE"),
    ("Aramayo Fritis Victor Marcos", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Aravena Arriagada Camilo Ernesto", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Aravena Arriagada Camilo Ernesto", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Araya Chanqueo Ignacio Isaac", "Consultoria", "PUERTO ANGAMOS, SALAR"),
    ("Arce Rojas Camilo Alfonso", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (NCEN), AMSA (ZALDIVAR)"),
    ("Barraza Lamas Pia Noelia", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Barreda Torres Felix Wilson", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Bernales Magnere Tomas Augusto", "Comunicaciones", "CANDELARIA, CASERONES"),
    ("Beroiza Rodriguez Daniela Andrea", "Consultoria", "BHP ESCONDIDA"),
    ("Bracamonte Aballai Carlos Pascual", "Consultoria", "BHP ESCONDIDA"),
    ("Bugueno Solar Sergio Alberto", "Comunicaciones", "AMSA (ANTUCOYA)"),
    ("Campos Llanca Luis Humberto", "Comunicaciones", "CODELCO DET"),
    ("Cancino Toloza Daniel Andres", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Carrasco Rojas Erick Fernando", "Comunicaciones", "CODELCO DET"),
    ("Carvallo Saez Micchelle Yamil", "Comunicaciones", "SQM"),
    ("Castillo Mendez Diego Antonio", "Comunicaciones", "FME"),
    ("Castro Rojas Katherina Fernanda", "Comunicaciones", "CANDELARIA"),
    ("Cataldo Leiva Paola Andrea", "Comunicaciones", "COSTOS DE SUBDIRECCION"),
    ("Cataldo Leiva Paola Andrea", "Consultoria", "COSTOS DE SUBDIRECCION"),
    ("Caucoto Meneses Carolina Angelica", "Consultoria", "BHP ESCONDIDA"),
    ("Cepeda Vivanco Pilar Victoria", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Cid Sandoval Nicolas Andre", "Comunicaciones", "AMSA (NCEN)"),
    ("Cruz Mora Mariela Concepcion", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Cuevas Cortes Fernanda Javiera", "Comunicaciones", "CMP"),
    ("Delgado Inostroza Paulina Alejandra", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Diaz Aguilar Gabriela Alexandra", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Diaz Herrera Nicolas Felipe", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Diaz Lara Camila", "Comunicaciones", "CODELCO CORP"),
    ("Echeverria Noton Loreto Cecilia", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Fernandez Ortiz Hernan Felipe", "Comunicaciones", "CODELCO CORP"),
    ("Freire Meza Graciela Constanza", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (NCEN), AMSA (ZALDIVAR)"),
    ("Freire Meza Graciela Constanza", "Consultoria", "BHP ESCONDIDA"),
    ("Fuentes Rubio Lenka Camila", "Comunicaciones", "CODELCO DET"),
    ("Garrido Yanez Hector Manuel", "Comunicaciones", "CODELCO DET"),
    ("Garro Castano Valentina", "Comunicaciones", "AMSA (NCEN)"),
    ("Gomez Crawford Isidora Paz", "Comunicaciones", "CODELCO EO, CODELCO CORP"),
    ("Gomez Moyano Camila Javiera", "Consultoria", "BHP ESCONDIDA"),
    ("Gomez Sanchez Fernanda Javiera", "Comunicaciones", "FME"),
    ("Gonzalez Gamboa Iris Lorena", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (ZALDIVAR)"),
    ("Guzman Cortes Abdiel Alexis", "Consultoria", "BHP ESCONDIDA"),
    ("Harrison Necochea Benjamin", "Comunicaciones", "COSTOS DE DIRECCION"),
    ("Harrison Necochea Victor Andres", "Consultoria", "COSTOS DE DIRECCION"),
    ("Harrison Necochea Victor Andres", "Comunicaciones", "COSTOS DE DIRECCION"),
    ("Heredia Duran Viviana Elizabeth", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Hernandez Suarez Valentina Paz", "Comunicaciones", "CODELCO DET"),
    ("Herrera Mauad Roberto Antonio", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Huidobro Maturana Fabiani Alejandro", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Huidobro Maturana Fabiani Alejandro", "Comunicaciones", "FME"),
    ("Illanes Caba Deborah Nicole", "Comunicaciones", "FME"),
    ("Iriarte Magadan Paula Amaya", "Comunicaciones", "CMP"),
    ("Jullian Roig Juan Francisco", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Kampf Roa Max Andreas", "Comunicaciones", "CODELCO EO, CODELCO CORP"),
    ("Kovacic Madariaga Tonkiza Dayann", "Consultoria", "BHP ESCONDIDA"),
    ("Lanoy Molina Maglenis Carolina", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Ledezma Hidalgo Alejandro Esteban", "Comunicaciones", "AMSA (NCEN)"),
    ("Lingua Moreno Aldo Javier", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Lopez Matamala Marcelo Andres", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Maluenda Acevedo Camila Alejandra", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Mancilla Ordenes Oscar Alonso", "Comunicaciones", "CMP"),
    ("Martinez Amenabar Eustaquio", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Maya Gonzalez Javiera Nicole", "Comunicaciones", "CEIM"),
    ("Maya Gonzalez Javiera Nicole", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Mella Cadiz Cristopher Andres", "Comunicaciones", "CODELCO DET"),
    ("Mellado Salazar Luis", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Meza Iriarte Edmundo Esteban Jesus", "Comunicaciones", "AMSA (ANTUCOYA)"),
    ("Middleton Bezanilla Javier Fernando", "Comunicaciones", "CODELCO CORP"),
    ("Miranda Humeres Patricio Javier", "Comunicaciones", "CODELCO DET"),
    ("Molina Tapia Alexis Rodrigo", "Consultoria", "BHP ESCONDIDA"),
    ("Montoya Lopez Diego Ignacio", "Comunicaciones", "CMP"),
    ("Moraga Morey Maria Jose", "Comunicaciones", "CMP"),
    ("Moraga Morey Maria Jose", "Consultoria", "CMP"),
    ("Morales Leiva David Eduardo", "Comunicaciones", "CODELCO CORP"),
    ("Moreno Saavedra Juan Patricio", "Comunicaciones", "CASERONES, KINROSS LOBO MARTE"),
    ("Munoz Baratta Maria Alejandra", "Comunicaciones", "CMP"),
    ("Munoz Espinoza Ricardo Hernan", "Consultoria", "BHP ESCONDIDA"),
    ("Munoz Vera Manuel Jesus", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Mura Gonzalez Minelly Dannay", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Navarro Lopez Javier Andres", "Comunicaciones", "CODELCO DET"),
    ("Neder Acosta Ulises Patricio", "Comunicaciones", "AMSA (CENTINELA)"),
    ("Olivares Vega Alejandra Hortensia", "Comunicaciones", "AMSA (CENTINELA)"),
    ("Ortiz Aguilera Sebastian Ignacio", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Ovando Vergara Macarena Francisca", "Comunicaciones", "GLENCORE"),
    ("Palma Zepeda Nancy Anarella", "Comunicaciones", "AMSA (CENTINELA)"),
    ("Parra Espinosa Karen Andrea", "Consultoria", "SALAR"),
    ("Pereira Molina Lorena Antonieta", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (ZALDIVAR)"),
    ("Perez Caro Gabriela Ximena", "Consultoria", "BHP ESCONDIDA"),
    ("Perez Caro Gabriela Ximena", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Pizarro Bravo Monica Isabel", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Pollmann Fleming Sibila Joaquina", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Ponce Vidal Claudia Ayleen", "Consultoria", "BHP ESCONDIDA"),
    ("Quintanilla Dominguez Sebastian Ignacio", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Quintanilla Dominguez Sebastian Ignacio", "Comunicaciones", "GLENCORE, CASERONES"),
    ("Ramirez Vega Jasmin Betsabe", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Ramos Galleguillos Javier Ignacio", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Ramos Valenzuela Felipe Antonio", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Reyes Guzman Mitzi Andrea", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Reyes Guzman Mitzi Andrea", "Comunicaciones", "PUERTO ANGAMOS, SQM"),
    ("Rivera Cerda Hernando Sebastian", "Comunicaciones", "AMSA (ANTUCOYA)"),
    ("Rivera Zarricueta Constanza Nicole", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Roa Abayay Marta Soledad", "Comunicaciones", "CODELCO CORP"),
    ("Rodas Araya Carlos Alejandro", "Comunicaciones", "CANDELARIA"),
    ("Rodriguez Correa Daniela", "Comunicaciones", "COSTOS DE DIRECCION"),
    ("Rodriguez Gonzalez Alberto Antonio", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Rodriguez Varela Maria Paz", "Comunicaciones", "CMP"),
    ("Romero Moraga Fernanda Maria", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Ronda Ortiz Antonia Ester", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Salazar Guerrero Tamara Jose", "Comunicaciones", "CANDELARIA"),
    ("Salinas Valdivia Omar Andres", "Comunicaciones", "CMP"),
    ("Salles Sapag Maria Bernardita", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Sanchez Cortes-Monroy Javiera Pilar", "Comunicaciones", "CMP"),
    ("Sanchez Marin Maria Jose", "Comunicaciones", "GLENCORE"),
    ("Silva Gatta Sebastian Andres", "Comunicaciones", "CODELCO DET"),
    ("Solar De La Maza Sofia Macarena", "Comunicaciones", "CODELCO EO, CODELCO CORP"),
    ("Solari Diaz Gino Guillermo", "Comunicaciones", "CEIM, FME"),
    ("Solari Diaz Gino Guillermo", "Consultoria", "COSTOS COORDINACION OPERACIONAL"),
    ("Sotomayor Villarroel Mauricio Andres", "Comunicaciones", "CANDELARIA, CASERONES, INFORME SINDICAL BHP"),
    ("Toledo Andrade Carla Andrea", "Comunicaciones", "CODELCO DET, KINROSS COMUNICACIONES"),
    ("Torres Gomez Andres Antonio", "Comunicaciones", "AMSA (ZALDIVAR)"),
    ("Trincado Huanchicay Rocio Abril", "Comunicaciones", "KINROSS COMUNICACIONES"),
    ("Valdes Tapia Josefa Antonieta", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (ZALDIVAR)"),
    ("Valenzuela Dellafiori Paula", "Comunicaciones", "COSTOS DE DIRECCION"),
    ("Valenzuela Dellafiori Paula", "Consultoria", "COSTOS DE DIRECCION"),
    ("Vallejos Opazo Matias", "Comunicaciones", "COSTOS COORDINACION OPERACIONAL"),
    ("Valverde Onate Karla Stefanie", "Comunicaciones", "CODELCO DET"),
    ("Vargas Moya Exequiel Ananias", "Comunicaciones", "CODELCO DET"),
    ("Vega Chelme Claudio Andres", "Consultoria", "BHP ESCONDIDA, FME"),
    ("Vega Velozo Valeria Andrea", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (ZALDIVAR)"),
    ("Veliz Saavedra Joao Humberto", "Consultoria", "BHP ESCONDIDA"),
    ("Vergara Pinnola Vannia Silvana", "Comunicaciones", "CMP"),
    ("Vidal Diaz Mauricio Antonio", "Comunicaciones", "AMSA (ANTUCOYA), AMSA (CENTINELA), AMSA (ZALDIVAR)"),
    ("Vilches Vergara Andrea Makarena", "Comunicaciones", "COSTOS ADMINISTRATIVOS"),
    ("Villarroel Perez Carmen Gloria", "Comunicaciones", "AMSA (NCEN)"),
    ("Worthington Ramirez Aida Constanza", "Comunicaciones", "CODELCO CORP"),
    ("Zamora Marchant Sebastian", "Comunicaciones", "CODELCO DET"),
    ("Zazzali Toledo Lorenzo Sebastian", "Comunicaciones", "COSTOS DE SUBDIRECCION"),
]

unique_names = set(normalize(row[0]) for row in user_assignments)
missing = []
for row in user_assignments:
    n = normalize(row[0])
    if n not in db_set and n not in [normalize(m) for m in missing]:
        missing.append(row[0])

print("=== NO ENCONTRADOS EN LA BASE DE DATOS ===")
for m in sorted(set(missing)):
    print(f"  - {m}")
print(f"\nTotal nombres únicos en listado: {len(unique_names)}")
print(f"No encontrados: {len(set(missing))}")

# Centros únicos
all_centers = set()
for _, _, centers in user_assignments:
    for c in centers.split(","):
        all_centers.add(c.strip())
print(f"\n=== CENTROS ÚNICOS ({len(all_centers)}) ===")
for c in sorted(all_centers):
    print(f"  - {c}")
